/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect, useState } from 'react';
import { ScrollMenu } from 'react-horizontal-scrolling-menu';
import { AiOutlineAppstoreAdd } from 'react-icons/ai';
import {
  IoPizzaOutline,
  IoFastFoodOutline,
  IoArrowUpCircleOutline,
} from 'react-icons/io5';
import { MdOutlineLocalDrink } from 'react-icons/md';
import { TbHome2, TbIceCream2, TbMeat } from 'react-icons/tb';

import { NavBar } from '@/components/NavBar';
import { Product } from '@/components/Product';
import { Search } from '@/components/Search';
import styles from '@/styles/pages/Home.module.scss';
import { IProduct } from '@/types/product';
import axios from 'axios';
import { GetStaticProps, InferGetStaticPropsType } from 'next';
import Head from 'next/head';

export default function Home({
  allProducts,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const [products, setProducts] = useState<IProduct[]>([]);
  const [scroll, setScroll] = useState(false);

  useEffect(() => {
    window.addEventListener('scroll', () => {
      if (window.scrollY > 300) {
        setScroll(true);
      } else {
        setScroll(false);
      }
    });
  }, []);

  useEffect(() => {
    setProducts(allProducts);
  }, [allProducts]);

  function handleSearch(value: string) {
    if (value.length > 0) {
      const filterProducts = allProducts.filter((product: IProduct) =>
        product.name.toLowerCase().includes(value.toLowerCase())
      );

      setProducts(filterProducts);
    } else {
      setProducts(allProducts);
    }
  }

  function handleChangeCategory(category: string) {
    if (category === 'all') {
      setProducts(allProducts);
      return;
    }

    setProducts(
      allProducts.filter((product: IProduct) => product.category === category)
    );
  }

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>
      <NavBar title="Restaurant Example" />
      <main className={styles.main}>
        {scroll ? null : <Search handleSearch={handleSearch} />}

        <div className={styles.products}>
          <div className={styles.products_title}>
            <h2>Produtos</h2>
          </div>
          <div className={styles.categories}>
            <ScrollMenu scrollContainerClassName={styles.scroll_container}>
              <div className={styles.list_categories}>
                <div
                  className={styles.category_item}
                  style={{
                    backgroundColor: '#70e000',
                  }}
                  onClick={() => {
                    handleChangeCategory('all');
                  }}
                >
                  <div className={styles.category_icon}>
                    <TbHome2 size={20} />
                  </div>
                  <div className={styles.category_title}>
                    <h2>Tudo</h2>
                  </div>
                </div>
                <div
                  className={styles.category_item}
                  onClick={() => {
                    handleChangeCategory('pizzas');
                  }}
                >
                  <div className={styles.category_icon}>
                    <IoPizzaOutline size={20} />
                  </div>
                  <div className={styles.category_title}>
                    <h2>Pizzas</h2>
                  </div>
                </div>
                <div
                  className={styles.category_item}
                  style={{
                    backgroundColor: '#e63946',
                  }}
                  onClick={() => {
                    handleChangeCategory('carnes');
                  }}
                >
                  <div className={styles.category_icon}>
                    <TbMeat size={20} />
                  </div>
                  <div className={styles.category_title}>
                    <h2>Carnes</h2>
                  </div>
                </div>
                <div
                  className={styles.category_item}
                  style={{
                    backgroundColor: '#457b9d',
                  }}
                  onClick={() => {
                    handleChangeCategory('bebidas');
                  }}
                >
                  <div className={styles.category_icon}>
                    <MdOutlineLocalDrink size={20} />
                  </div>
                  <div className={styles.category_title}>
                    <h2>Bebidas</h2>
                  </div>
                </div>
                <div
                  className={styles.category_item}
                  style={{
                    backgroundColor: '#00bbf9',
                  }}
                  onClick={() => {
                    handleChangeCategory('sobremesas');
                  }}
                >
                  <div className={styles.category_icon}>
                    <TbIceCream2 size={20} />
                  </div>
                  <div
                    className={styles.category_title}
                    style={{
                      width: '154px',
                    }}
                  >
                    <h2>Sobremesas</h2>
                  </div>
                </div>
                <div
                  className={styles.category_item}
                  style={{
                    backgroundColor: '#f07167',
                  }}
                  onClick={() => {
                    handleChangeCategory('lanches');
                  }}
                >
                  <div className={styles.category_icon}>
                    <IoFastFoodOutline size={20} />
                  </div>
                  <div className={styles.category_title}>
                    <h2>Lanches</h2>
                  </div>
                </div>
                <div
                  className={styles.category_item}
                  style={{
                    backgroundColor: '#2b2d42',
                  }}
                  onClick={() => {
                    handleChangeCategory('outros');
                  }}
                >
                  <div className={styles.category_icon}>
                    <AiOutlineAppstoreAdd size={20} />
                  </div>
                  <div className={styles.category_title}>
                    <h2>Outros</h2>
                  </div>
                </div>
              </div>
            </ScrollMenu>
          </div>
          <div className={styles.products_list}>
            {products.length > 0 ? (
              products.map((product) => (
                <Product key={product.id} data={product} />
              ))
            ) : (
              <p>Nenhum produto encontrado</p>
            )}
          </div>
        </div>

        <div className={styles.back_to_top}>
          {scroll ? (
            <button
              type="button"
              onClick={() => {
                window.scrollTo(0, 0);
              }}
            >
              <IoArrowUpCircleOutline size={40} />
            </button>
          ) : null}
        </div>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const { data } = await axios.get<IProduct[]>(
    process.env.DEVELOPING === 'true'
      ? `${process.env.URL}/api/products`
      : `https://espeto-gaucho.vercel.app/api/products`
  );

  if (!data) {
    return {
      props: {
        allProducts: [],
      },
    };
  }

  return {
    props: {
      allProducts: data,
    },
  };
};
