import { Header } from '@/components/Header';
import styles from '@/styles/pages/Profile.module.scss';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>
      <main className={styles.main}>
        <Header title="Perfil" home={true} />
        <h1>Em Desenvolvimento...</h1>
      </main>
    </>
  );
}
